// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: astar.proto

#include "astar.pb.h"
#include "astar.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace astar {

static const char* AStar_method_names[] = {
  "/astar.AStar/doAStar",
};

std::unique_ptr< AStar::Stub> AStar::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AStar::Stub> stub(new AStar::Stub(channel));
  return stub;
}

AStar::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_doAStar_(AStar_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AStar::Stub::doAStar(::grpc::ClientContext* context, const ::astar::Request& request, ::astar::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::astar::Request, ::astar::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_doAStar_, context, request, response);
}

void AStar::Stub::experimental_async::doAStar(::grpc::ClientContext* context, const ::astar::Request* request, ::astar::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::astar::Request, ::astar::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_doAStar_, context, request, response, std::move(f));
}

void AStar::Stub::experimental_async::doAStar(::grpc::ClientContext* context, const ::astar::Request* request, ::astar::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_doAStar_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::astar::Reply>* AStar::Stub::PrepareAsyncdoAStarRaw(::grpc::ClientContext* context, const ::astar::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::astar::Reply, ::astar::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_doAStar_, context, request);
}

::grpc::ClientAsyncResponseReader< ::astar::Reply>* AStar::Stub::AsyncdoAStarRaw(::grpc::ClientContext* context, const ::astar::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdoAStarRaw(context, request, cq);
  result->StartCall();
  return result;
}

AStar::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AStar_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AStar::Service, ::astar::Request, ::astar::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AStar::Service* service,
             ::grpc::ServerContext* ctx,
             const ::astar::Request* req,
             ::astar::Reply* resp) {
               return service->doAStar(ctx, req, resp);
             }, this)));
}

AStar::Service::~Service() {
}

::grpc::Status AStar::Service::doAStar(::grpc::ServerContext* context, const ::astar::Request* request, ::astar::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace astar

