# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/lucas/warzone2100;/home/lucas/warzone2100/src")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMMAND "/usr/bin/cpack")
set(CPACK_COMPONENTS_ALL "Core;Data;Docs;Info;Languages;Fonts;Manpages")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENTS_GROUPING "ALL_COMPONENTS_IN_ONE")
set(CPACK_COMPONENT_CORE_DEPENDS "Data;Docs;Info")
set(CPACK_COMPONENT_CORE_DESCRIPTION "Application")
set(CPACK_COMPONENT_CORE_DISPLAY_NAME "Application")
set(CPACK_COMPONENT_CORE_GROUP "CoreGroup")
set(CPACK_COMPONENT_CORE_REQUIRED "ON")
set(CPACK_COMPONENT_DATA_DESCRIPTION "Data Files")
set(CPACK_COMPONENT_DATA_DISPLAY_NAME "Data Files")
set(CPACK_COMPONENT_DATA_GROUP "CoreGroup")
set(CPACK_COMPONENT_DATA_REQUIRED "ON")
set(CPACK_COMPONENT_DOCS_DESCRIPTION "Documentation")
set(CPACK_COMPONENT_DOCS_DISPLAY_NAME "Documentation")
set(CPACK_COMPONENT_DOCS_GROUP "CoreGroup")
set(CPACK_COMPONENT_DOCS_REQUIRED "ON")
set(CPACK_COMPONENT_FONTS_DESCRIPTION "Fonts")
set(CPACK_COMPONENT_FONTS_DISPLAY_NAME "Fonts")
set(CPACK_COMPONENT_FONTS_GROUP "CoreGroup")
set(CPACK_COMPONENT_FONTS_REQUIRED "ON")
set(CPACK_COMPONENT_GROUP_COREGROUP_DESCRIPTION "The core files required to run Warzone 2100.")
set(CPACK_COMPONENT_GROUP_COREGROUP_DISPLAY_NAME "Core files")
set(CPACK_COMPONENT_GROUP_COREGROUP_REQUIRED "ON")
set(CPACK_COMPONENT_INFO_DESCRIPTION "Info Files")
set(CPACK_COMPONENT_INFO_DISPLAY_NAME "Info")
set(CPACK_COMPONENT_INFO_GROUP "CoreGroup")
set(CPACK_COMPONENT_INFO_REQUIRED "ON")
set(CPACK_COMPONENT_MANPAGES_GROUP "CoreGroup")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS "ON")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Innovative 3D real-time strategy
 In Warzone 2100 you command the forces of “The Project” in a battle to rebuild the world after mankind has been nearly destroyed by nuclear missiles.
 .
 The game offers campaign, tutorial, multi-player and single-player skirmish modes. An extensive tech tree with over 400 different technologies, combined with the unit design system, allows for a wide variety of possible units and tactics. Play versus AI bots in local skirmishes (or as added teammates / enemies in multiplayer), and practice your skills with endless replayability.
 .
 Warzone 2100 was originally created by Pumpkin Studios and published by Eidos Interactive, and was open-sourced in 2004. It has been developed, maintained, and improved by the community ever since, under the banner of the “Warzone 2100 Project”.
 .
 This package does not include the campaign video sequences - please see the Warzone 2100 website for details on how to download and install them.")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://wz2100.net/")
set(CPACK_DEBIAN_PACKAGE_NAME "warzone2100")
set(CPACK_DEBIAN_PACKAGE_SECTION "games")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/lucas/warzone2100/src;warzone2100;ALL;/")
set(CPACK_INSTALL_PREFIX "/home/lucas/wz/install")
set(CPACK_INSTALL_SCRIPT "/home/lucas/warzone2100/src/autorevisionForSourcePackage.cmake")
set(CPACK_MODULE_PATH "/home/lucas/warzone2100/cmake")
set(CPACK_NSIS_DISPLAY_NAME "Warzone 2100 0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Warzone 2100 0.1.1")
set(CPACK_OUTPUT_CONFIG_FILE "/home/lucas/warzone2100/src/CPackConfig.cmake")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/lucas/warzone2100/pkg/Description.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "warzone2100 built using CMake")
set(CPACK_PACKAGE_FILE_NAME "warzone2100")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://wz2100.net")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Warzone 2100 0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Warzone 2100 0.1.1")
set(CPACK_PACKAGE_NAME "Warzone 2100")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Warzone 2100 Project")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_PROJECT_CONFIG_FILE "/home/lucas/warzone2100/src/CPackConfigVersion.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "/home/lucas/warzone2100/COPYING")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.16/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_GROUP "Amusements/Games")
set(CPACK_RPM_PACKAGE_LICENSE "GPLv2+ and CC-BY-SA")
set(CPACK_RPM_PACKAGE_SUMMARY "Innovative 3D real-time strategy")
set(CPACK_RPM_PACKAGE_URL "https://wz2100.net/")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TXZ")
set(CPACK_SOURCE_IGNORE_FILES "\\.#;/#;/\\.git;/\\.svn;/\\.hg/;/\\.bzr/;/\\.ci/;/\\.github/;/\\.cirrus.yml;/\\.lgtm.yml;/\\.travis.yml;/\\appveyor.yml;/\\azure-pipelines.yml;/\\crowdin.yml;~$;\\.DS_Store$;/build/;/data/sequences.wz;/build_tools/autorevision.cache;/macosx/build/;/macosx/external/.*/;/vcpkg/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/lucas/warzone2100/src/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "warzone2100")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/lucas/warzone2100/src/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
